name          'jbouse-roundcube'
version       '0.1.0'
source        'UNKNOWN'
author        'jbouse'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
dependency 'puppetlabs/apt', '>= 1.6.0'
